  - name: install mysql
    action: apt pkg=mysql-server,mytop,python-mysqldb state=latest update-cache=yes force=yes install_recommends=yes

  - name: Start the MySQL service
    action: service name=mysql state=started

  - name: Mysql Configuration file
    action: template src=../../webserver/templates/etc-mysql-my-cnf.j2 dest=/etc/mysql/my.cnf
    notify:
     - restart mysql
