  - name: install nginx
    action: apt pkg=nginx state=latest update-cache=yes force=yes install_recommends=yes

  - name: install nginx.conf  
    action: template src=../../webserver/templates/etc-nginx-nginx-conf.j2 dest=/etc/nginx/nginx.conf
    notify:
      - restart nginx

  - name: install nginx conf
    action: copy src=files/nginx_{{item}} dest=/etc/nginx/conf.d/{{item}}.conf
    with_items: sites
    notify:
      - restart nginx
#    when: ansible_os_family == "Debian" and ansible_lsb.major_release|int >= 7
